### Markdown

All as latex

$$ to the sides of formulas

### Include

In [3]:
import numpy as np                        # Math
import scipy.stats                        # Statistics
from matplotlib import pyplot as plt      # Plots

### Useful

In [ ]:
np.linspace(min, max, num=50)
np.mean(array)
np.std(array)    # dof can be added if needed
np.array([elements])
np.zeros(N)      # array of zeros, with N elements
np.sum(array)
array.sort() 
array.shape()
array.size()

In [ ]:
# I can work vectorially !!!
bin_mids = (bins[1:] + bins[:-1]) / 2    # mid location of bins

### Distributions

#### Gaussian
https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.stats.norm.html


In [ ]:
from scipy.stats import norm
# Alternative: use everywhere scipy.stats.norm

# "Initialize" the distribution
gauss = norm(loc=0,scale=sigma)     # loc = mean, scale=std deviation

# Generate random numbers
R = norm.rvs(loc=0, scale=1, size=N)
R = gauss.rvs(size=N)
R = np.random.normal(loc=mean, scale=sigma, size=N)

# Pdf given the points (to plot continuos distrib)
f = norm.pdf(x, loc=0, scale=1)
f = gauss.pdf(x)

#### Uniform

In [ ]:
# Generate random numbers
u = np.random.uniform(min, max, npoints) 

### Histogram

In [ ]:
plt.hist(x, bins=nbins, color=None, label=None)

# density = True --> return height of the bins (of the NORMALIZED hist)
# cumulative = True --> cumulative histogram
# histtype{'bar', 'barstacked', 'step', 'stepfilled'}, default: 'bar'} --> type of hist
# log = True --> the hist axis will be set to a log scale.

# Returns --> n (array): values of the histogram bins
#             bins (array): edges of the bins

Arguments:
- density = True --> return height of the bins (of the NORMALIZED hist)
- cumulative = True --> cumulative histogram
- histtype{'bar', 'barstacked', 'step', 'stepfilled'} --> type of hist (default: 'bar')
- log = True --> the hist axis will be set to a log scale.

NB: bins = array --> it defines the hist binning using the array

Returns:
- n (array): values of the histogram bins
- bins (array): edges of the bins

In [ ]:
# form an array with elements smaller than (u,q) (where u,q corresponding vectors)

counts, bins = np.histogram(data, bins=nbin, density=True)

disth = scipy.stats.rv_histogram((counts,bins)) # crea func a gradino che segue l'istogramma 
mask = u<=disth.pdf(q) # assess whether u <= q(x_i)
monte_carlo = q[mask] # reject all points that don't pass, using masking

### Plot

In [ ]:
plt.plt(x, y)
plt.plt(x, y, x1, y1, x2, y2)  # More than one set per time

plt.scatter(x,y)  # Plot a punti

# I can call multiple plot, then I can add the options such as
plt.loglog()  # log scale
plt.legend()

# And at the end
plt.show() 

### Interpolation

In [ ]:
f_interp = scipy.interpolate.interp1d(y, x)

### Sklearn data

The data need to be of shape (N,1), not (N,)

In [4]:
x=np.linspace(0, 5, 6)
print(x, x.shape)
print(x[np.newaxis,:], x[np.newaxis,:].shape)
print(x[:,np.newaxis], x[:,np.newaxis].shape)

[0. 1. 2. 3. 4. 5.] (6,)
[[0. 1. 2. 3. 4. 5.]] (1, 6)
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]] (6, 1)


### Others

In [ ]:
np.unique(array) # new array without repetitions
plt.axhline(y=0, xmin=0, xmax=1) # Add a horizontal line across the Axes.