### Markdown

All as latex

$$ to the sides of formulas

### Include

In [3]:
import numpy as np                        # Math
import scipy.stats                        # Statistics
from matplotlib import pyplot as plt      # Plots

### Useful

In [ ]:
<span style="color:red"> word </span> 

In [ ]:
np.linspace(min, max, num=50)
np.mean(array)
np.std(array)    # dof can be added if needed
np.array([elements])
np.zeros(N)      # array of zeros, with N elements
np.sum(array)
np.arange(1, 10) # numeri (interi) fra 1 e 10
t,y,yerr=(np.array).T # traspone data (matrice 100x3) in 3x100 e assegna ognuna delle 3 righe ad un vettore

array.sort() 
array.shape()
array.size()
array.astype(int)  # convertion in int
array.reshape(-1, 1)  # reshape the array with only one column
np.unique(array)   # new array deleting repetitions

str(number)   # convertion in string

In [ ]:
# I can work vectorially !!!
bin_mids = (bins[1:] + bins[:-1]) / 2    # mid location of bins

In [ ]:
# Initialize a void vector of N components
models = [None for i in range(N)]

Read files

In [ ]:
# npy files
input_file_path = '/Users/giulia/coding/astrostat/astrostatistics_bicocca_2024/solutions/transient.npy'
data = np.load(input_file_path)

# other files
input_file_path = '/Users/giulia/coding/astrostat/astrostatistics_bicocca_2024/solutions/transient.npy'
input_file = open(input_file_path)
data = input_file.read()
input_file.close()

### Distributions

#### Gaussian
https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.stats.norm.html


In [ ]:
from scipy.stats import norm
# Alternative: use everywhere scipy.stats.norm

# "Initialize" the distribution
gauss = norm(loc=0,scale=sigma)     # loc = mean, scale=std deviation

# Generate random numbers
R = norm.rvs(loc=0, scale=1, size=N)
R = gauss.rvs(size=N)
R = np.random.normal(loc=mean, scale=sigma, size=N)

# Pdf given the points (to plot continuos distrib)
f = norm.pdf(x, loc=0, scale=1)
f = gauss.pdf(x)

#### Uniform

In [ ]:
# Generate random numbers
u = np.random.uniform(min, max, npoints) 

### Histogram

In [ ]:
plt.hist(x, bins=nbins, color=None, label=None)

# density = True --> return height of the bins (of the NORMALIZED hist)
# cumulative = True --> cumulative histogram
# histtype{'bar', 'barstacked', 'step', 'stepfilled'}, default: 'bar'} --> type of hist
# log = True --> the hist axis will be set to a log scale.

# Returns --> n (array): values of the histogram bins
#             bins (array): edges of the bins

Arguments:
- density = True --> return height of the bins (of the NORMALIZED hist)
- cumulative = True --> cumulative histogram
- histtype{'bar', 'barstacked', 'step', 'stepfilled'} --> type of hist (default: 'bar')
- log = True --> the hist axis will be set to a log scale.

NB: bins = array --> it defines the hist binning using the array

Returns:
- n (array): values of the histogram bins
- bins (array): edges of the bins

### Mask

In [ ]:
mask = u<=condition # assess whether u <= q(x_i)
q_new = q[mask] # reject all points that don't pass, using masking

### Plot

In [ ]:
plt.plt(x, y)
plt.plt(x, y, x1, y1, x2, y2)  # More than one set per time

plt.scatter(x,y)  # Plot a punti

# I can call multiple plot, then I can add the options such as
plt.loglog()  # log scale
plt.legend()

# Add a horizontal line across the Axes
plt.axhline(y=0, xmin=0, xmax=1).

plt.xlabel('label on x axis')
plt.ylabel('label on y axis')
plt.xticks(range(min(x), max(x) + 1))

# And at the end
plt.show() 

### Interpolation

In [ ]:
f_interp = scipy.interpolate.interp1d(y, x)

### Likelihood

In [ ]:
#log likelihood when fitting polynomials to data
def LogLikelihood(theta, data, model):
    x, y, sigma_y = data.T
    y_fit = model(x, theta)
    return -0.5 * np.sum((y-y_fit)**2 / sigma_y**2 ) 

### Sklearn data

The data need to be of shape (N,1), not (N,)

In [4]:
x=np.linspace(0, 5, 6)
print(x, x.shape)
print(x[np.newaxis,:], x[np.newaxis,:].shape)
print(x[:,np.newaxis], x[:,np.newaxis].shape)

[0. 1. 2. 3. 4. 5.] (6,)
[[0. 1. 2. 3. 4. 5.]] (1, 6)
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]] (6, 1)


In [5]:
# another option
x1 = x.reshape(-1, 1)
print(x1)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]


**Freedman-Diaconis rule**

$$\Delta_b = \frac{2(q_{75}-q_{25})}{N^{1/3}} = \frac{2.7\sigma_G}{N^{1/3}}.$$  

In [ ]:
from astroML import stats as astroMLstats

sigmaG2 = astroMLstats.sigmaG(M_irr)

binsize = 2.7*sigmaG2/(N**(1/3))

binsG = np.append(np.arange(start=M_irr.min(), stop=M_irr.max(), step=binsize) , M_irr.max()) #Complete

plt.hist(M_irr, bins=binsG, density=True)
plt.show()

**Plot using a KDE**

In [ ]:
from sklearn.neighbors import KernelDensity

def kde_sklearn(data, bandwidth, kernel):
    kde_skl = KernelDensity(bandwidth = bandwidth, kernel=kernel)
    kde_skl.fit(data[:, np.newaxis])
    log_pdf = kde_skl.score_samples(xgrid[:, np.newaxis])

    return np.exp(log_pdf)

bandwidth=0.05
kernel="epanechnikov" # or "gauss"
PDFtophat = kde_sklearn(M_irr,bandwidth,kernel) 

x = np.linspace(min,max,N) 

plt.plot(x,PDFtophat)
plt.show()

### Others

In [ ]:
# Barra di avanzamento
Mirr = [scipy.integrate.quad(lambda f: integrand(f,xt), 1/2**0.5,1)[0] for xt in tqdm(x)]
